### EXAMPLE docker-compose.yml FILE ###
version: '3.8'

services:
    ### APP (php-fpm) ##############################################
    app:
        build:
            context: ./docker/app
        volumes:
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
            - ./docker/app/supervisor-logs:/var/log
            - .:/var/www/html:delegated
        expose:
            - "9000"
        networks:
            - "mynetwork"

networks:
    mynetwork:
        driver: "bridge"
