#!/bin/sh
set -e

# run last minute build tools just for local dev
# this file should just be used to override on local dev in a compose file

# ensure bind mount permissions are what we need
echo "running 'chown -R :www-data'. It will take some time..." >&2
chown -R :www-data /var/www/html/bootstrap/cache/
chown -R :www-data /var/www/html/public/
chown -R :www-data /var/www/html/storage/
chown -R :www-data /var/www/html/vendor/

echo "running 'chmod -R g+w'. It will take some time..." >&2
chmod -R g+w /var/www/html/bootstrap/cache/
chmod -R g+w /var/www/html/public/
chmod -R g+w /var/www/html/storage/
chmod -R g+w /var/www/html/vendor/

# put here any production bash scripts if need
sudo -u www-data composer dump-autoload -o
ls -al
ls -al ./vendor
sudo -u www-data php artisan migrate --seed --force
sudo -u www-data php artisan clear-compiled
sudo -u www-data php artisan config:clear
sudo -u www-data php artisan cache:clear
sudo -u www-data php artisan config:cache
sudo -u www-data php artisan view:cache
sudo -u www-data php artisan route:cache

exec "$@"
