#!/bin/sh
# todo think if we need `-e` option: 'Exit immediately if a command exits with a non-zero status.'
# set -e

# run last minute build tools just for local dev
# this file should just be used to override on local dev in a compose file

# ensure bind mount permissions are what we need
chown -R :www-data /var/www/html/bootstrap/cache/
chown -R :www-data /var/www/html/public/
chown -R :www-data /var/www/html/storage/

chmod -R g+w /var/www/html/bootstrap/cache/
chmod -R g+w /var/www/html/public/
chmod -R g+w /var/www/html/storage/

exec "$@"
